apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- rollouts.yaml

namespace: dev

images:
- name: ghcr.io/warapong-pj/sample-app
  newTag: dev-a80786e

patches:
- target:
    kind: Deployment
    name: sample-app
  path: patch-deployment.yaml