apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

images:
- name: ghcr.io/warapong-pj/sample-app
  newTag: dev-47828e9

patches:
- target:
    kind: Deployment
    name: sample-app
  path: patch-deployment.yaml