apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

images:
- name: ghcr.io/warapong-pj/sample-kustomize
  newTag: v1.0.0

patches:
- target:
    kind: Deployment
    name: sample-app
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sample-app
    spec:
      template:
        spec:
          containers:
          - name: sample-app
            resources:
              requests:
                memory: "64Mi"
                cpu: "10m"
              limits:
                memory: "128Mi"
                cpu: "100m"
