name: Build pipeline

on: 
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      application:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login to github packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push container image to container registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.application }}:${{ inputs.version }}
