name: workflow
on: 
  repository_dispatch:
    types:
      - test
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          #!/bin/sh

          APP_DIR="${{ github.event.client_payload.application }}/${{ github.event.client_payload.environment }}"
          echo $APP_DIR
          
          if [ ! -d $APP_DIR ]
          then
            echo "directory dose not existing"
          fi