name: workflow
on: 
  repository_dispatch:
    types:
      - test
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          #!/bin/sh

          set -xe
          
          which kustomize

          APP_DIR="${{ github.event.client_payload.application }}/overlay/${{ github.event.client_payload.environment }}"
          
          if [ ! -d $APP_DIR ]
          then
            echo "directory dose not existing"
            exit 1
          fi

          cd $APP_DIR
          kustomize edit set image ghcr.io/${{ github.actor }}/sample-app:${{ github.event.client_payload.version }}
          ./kubectl kustomize
          
          cd -
          git config --global user.email "warapong.pj@gmail.com"
          git config --global user.name "warapong-pj"
          git add -A
          git commit -m "ci: update ${{ github.event.client_payload.application }} image tag ${{ github.event.client_payload.version }}"
          git push origin ${{ github.ref_name }}
          