name: workflow
on: 
  repository_dispatch:
    types:
      - test
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          #!/bin/sh

          if [ ! -d ${{ github.event.client_payload.application }} ]
          then
            echo "directory dose not existing"
          fi