name: workflow
on: 
  repository_dispatch:
    types:
      - test
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow"
      - name: Checkout
        uses: actions/checkout@v2