name: test

on:
  repository_dispatch:
    types:
      - test_event

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test trigger"
          echo "payload registry '${{ github.event.client_payload.registry }}"
          echo "payload application '${{ github.event.client_payload.application }}'"
          echo "payload version '${{ github.event.client_payload.version }}'"
          echo "payload environment '${{ github.event.client_payload.environment }}'"