name: test

on:
  repository_dispatch:
    types:
      - test_event

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source codee
        uses: actions/checkout@v3
      - name: update kubernetes manifest
        run: |
          #!/bin/sh

          set -e

          echo "test trigger"
          echo "payload registry '${{ github.event.client_payload.registry }}'"
          echo "payload application '${{ github.event.client_payload.application }}'"
          echo "payload version '${{ github.event.client_payload.version }}'"
          echo "payload environment '${{ github.event.client_payload.environment }}'"
          
          if ! command -v kustomize &> /dev/null
          then
              curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          fi

          APP_DIR="${{ github.event.client_payload.application }}/overlay/${{ github.event.client_payload.environment }}"

          if [ ! -d $APP_DIR ]
          then
            echo "directory dose not existing"
            exit 1
          fi

          # cd $APP_DIR
          # kustomize edit set image ${{ github.event.client_payload.registry }}/${{ github.event.client_payload.application }}:${{ github.event.client_payload.version }}
          # kustomize build