name: test

on:
  workflow_dispatch:
    inputs:
      registry:
        required: true
        type: string
      application:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  log-the-inputs:
    uses: warapong-pj/target-repo/.github/workflows/pipeline.yml@main
    with:
      registry: "test"
      application: "test"
      version: "test"
      