name: test

on:
  workflow_dispatch:
    inputs:
      registry:
        required: true
        type: string
      application:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: warapong-pj/target-repo/.github/workflows/pipeline.yml