name: test

on:
  repository_dispatch:
    types:
      - test_event

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test trigger"
          echo "payload Foo '${{ github.event.client_payload.test_param1 }}'"
          echo "payload Foo '${{ github.event.client_payload.test_param2 }}'"