name: test

on:
  repository_dispatch:
    types:
      - test_event

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: set short commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      version-tag: ${{ steps.vars.outputs.sha_short }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: test pipeline
        run: |
          ls ${{ github.event.client_payload.application }}

          FILE="${{ github.event.client_payload.application }}/values-${{ github.event.client_payload.environment }}"
          if [ ! -d $FILE ]
          then
            echo "file dose not existing"
            exit 1
          fi

    # needs: get-version
    # uses: warapong-pj/reusable-workflows/.github/workflows/update-kubernetes-manifest-with-helm.yaml@dev
    # with:
    #   registry: ${{ github.event.client_payload.registry }}
    #   application: ${{ github.event.client_payload.application }}
    #   version: ${{ github.event.client_payload.version }}
    #   environment: ${{ github.event.client_payload.environment }}